USE [master]
GO

/****** Object:  Database [master_pol_enn]    Script Date: 16.03.2025 18:16:39 ******/
CREATE DATABASE [master_pol_enn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'master_pol_enn_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.EWYANG\MSSQL\DATA\master_pol_enn.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'master_pol_enn_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.EWYANG\MSSQL\DATA\master_pol_enn.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [master_pol_enn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [master_pol_enn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [master_pol_enn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [master_pol_enn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [master_pol_enn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [master_pol_enn] SET ARITHABORT OFF 
GO

ALTER DATABASE [master_pol_enn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [master_pol_enn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [master_pol_enn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [master_pol_enn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [master_pol_enn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [master_pol_enn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [master_pol_enn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [master_pol_enn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [master_pol_enn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [master_pol_enn] SET  ENABLE_BROKER 
GO

ALTER DATABASE [master_pol_enn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [master_pol_enn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [master_pol_enn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [master_pol_enn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [master_pol_enn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [master_pol_enn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [master_pol_enn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [master_pol_enn] SET RECOVERY FULL 
GO

ALTER DATABASE [master_pol_enn] SET  MULTI_USER 
GO

ALTER DATABASE [master_pol_enn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [master_pol_enn] SET DB_CHAINING OFF 
GO

ALTER DATABASE [master_pol_enn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [master_pol_enn] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [master_pol_enn] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [master_pol_enn] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [master_pol_enn] SET QUERY_STORE = ON
GO

ALTER DATABASE [master_pol_enn] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [master_pol_enn] SET  READ_WRITE 
GO

