//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master_pol_enn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class master_pol_ennEntities : DbContext
    {
        private static master_pol_ennEntities db;
        public static master_pol_ennEntities GetContext()
        {
            if (db == null)
            {
                db = new master_pol_ennEntities();
            }
            return db;
        }
        public master_pol_ennEntities()
            : base("name=master_pol_ennEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Material_type_import> Material_type_import { get; set; }
        public virtual DbSet<Partner_products_import> Partner_products_import { get; set; }
        public virtual DbSet<Partners_import> Partners_import { get; set; }
        public virtual DbSet<Product_type_import> Product_type_import { get; set; }
        public virtual DbSet<Products_import> Products_import { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
