//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master_pol_enn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type_import
    {
        public string Тип_материала { get; set; }
        public Nullable<double> Процент_брака_материала_ { get; set; }
        public int id_material_type { get; set; }
    }
}
