//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master_pol_enn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_import
    {
        public int id_partner_products { get; set; }
        public Nullable<int> id_products { get; set; }
        public Nullable<int> id_partners { get; set; }
        public Nullable<double> Количество_продукции { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
    
        public virtual Partners_import Partners_import { get; set; }
        public virtual Products_import Products_import { get; set; }
    }
}
