//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master_pol_enn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_import()
        {
            this.Partner_products_import = new HashSet<Partner_products_import>();
        }
    
        public int id_products { get; set; }
        public Nullable<int> id_product_type { get; set; }
        public string Наименование_продукции { get; set; }
        public Nullable<double> Артикул { get; set; }
        public Nullable<double> Минимальная_стоимость_для_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products_import> Partner_products_import { get; set; }
        public virtual Product_type_import Product_type_import { get; set; }
    }
}
