//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master_pol_enn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_type_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_type_import()
        {
            this.Products_import = new HashSet<Products_import>();
        }
    
        public int id_product_type { get; set; }
        public string Тип_продукции { get; set; }
        public Nullable<double> Коэффициент_типа_продукции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_import> Products_import { get; set; }
    }
}
